### ISSUE TITLE
Please mention format GET parameter in the quick start guide

### ISSUE THREAD

**Issue by swatson314159** [felixge/fgprof#1]
In my first test of fgprof I profiled my app by curling a remote host from another remote host where neither have go tools installed, copying the artifact local for analysis. I was expecting the pprof format as the default based on my reading of the quick start.  It took a bit of digging through the source to find `guessFormat` in handler.go to figure out why I was getting text vs binary output.  Your quick start guide is excellent, but a quick mention of the extra GET parameter somewhere on that first page would have saved me significant time.

**Comment by felixge** [comment]
@swatson314159 thanks for reporting this. PTAL at https://github.com/felixge/fgprof/pull/2 and let me know if you think that's a good solution or not. : )

**Comment by swatson314159** [comment]
my full response is on your PR: https://github.com/felixge/fgprof/pull/2#pullrequestreview-440102418

Thank you for responding so soon!

**Comment by felixge** [comment]
Implemented in https://github.com/felixge/fgprof/pull/2 . Thanks for reporting this!
