### ISSUE TITLE
Default time to 30s, to align with the pprof/profile default timeout

### ISSUE THREAD

**Issue by howardjohn** [felixge/fgprof#3]
Currently if you call the standard pprof endpoint without `?timeout` set, it will default to 30. With fgprof, this just fails. It would be nice to retain this defaulting behavior.

**Comment by felixge** [comment]
@howardjohn good idea, thx : ).

PTAL at https://github.com/felixge/fgprof/pull/4 and confirm if that's what you had in mind.

**Comment by felixge** [comment]
Fixed in https://github.com/felixge/fgprof/pull/4
